<form id="<?php echo $this->element->getId();?>" class="<?php echo $this->element->getAttrib('class');?>" action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod();?>" enctype="<?php echo $this->element->getEncType();?>">
    <fieldset>
        <div class="row">
            <div class="col-md-6">                                             
                <div class="form-group">
                    <?php echo $this->{$this->element->email->helper}(
                        $this->element->email->getName(),
                        $this->element->email->getValue(),
                        $this->element->email->getAttribs()
                    );?>                       
                    <?php if(($this->element->email->getMessages())){ echo  $this->formErrors($this->element->email->getMessages());}?>                   
                </div>                 
            </div>                                          
        </div>
        <?php echo $this->{$this->element->submit_subscriber->helper}(
            $this->element->submit_subscriber->getName(),
            $this->element->submit_subscriber->getValue(),  
            $this->element->submit_subscriber->getAttribs()
        );?>
    </fieldset>
</form>
<div class="clear"></div>
<script type="text/javascript">
$(document).ready(function() {
	$('#<?php echo $this->element->getId();?>').validationEngine('attach', {promptPosition : "centerRight"});
});
</script>
