<form id="<?php echo $this->element->getId();?>" class="<?php echo $this->element->getAttrib('class');?>" action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod();?>" enctype="<?php echo $this->element->getEncType();?>">
    <div class="box-body">                                                 
        <div class="form-group">
            <?php echo $this->{$this->element->title->helper}(
                $this->element->title->getName(),
                $this->element->title->getValue(),
                $this->element->title->getAttribs()
            );?>                    
            <?php if(($this->element->title->getMessages())){ echo  $this->formErrors($this->element->title->getMessages());}?>
        </div>                                                  
        <div class="form-group">
            <?php echo $this->{$this->element->message->helper}(
                $this->element->message->getName(),
                $this->element->message->getValue(),
                $this->element->message->getAttribs()
            );?>                    
            <?php if(($this->element->message->getMessages())){ echo  $this->formErrors($this->element->message->getMessages());}?>
        </div>                                                  
        <div class="form-group">
            <?php echo $this->{$this->element->image->helper}(
                $this->element->image->getName(),
                $this->element->image->getValue(),
                $this->element->image->getAttribs()
            );?>                    
            <?php if(($this->element->image->getMessages())){ echo  $this->formErrors($this->element->image->getMessages());}?>
        </div>
        <div class="form-group">
            <div class="radio">
                <label>
                  <input type="radio" name="clienti" id="all" value="1" checked>
                  Toata lista
                </label>
                <label>
                  <input type="radio" name="clienti" id="some" value="2">
                  Selecteaza persoane
                </label>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->{$this->element->emails->helper}(
                $this->element->emails->getName(),
                $this->element->emails->getValue(),
                $this->element->emails->getAttribs(),
                $this->element->emails->getMultiOptions()
            );?>                    
            <?php if(($this->element->emails->getMessages())){ echo  $this->formErrors($this->element->emails->getMessages());}?>
            <small>CTRL+click pentru a selecta mai multe</small>
        </div>
        <?php echo $this->{$this->element->submit->helper}(
            $this->element->submit->getName(),
            $this->element->submit->getValue(),
            $this->element->submit->getAttribs()
        );?>
    </div>
</form>
<div class="clear"></div>
<script type="text/javascript">
$(document).ready(function() {   
    $('#<?php echo $this->element->getId();?>').validationEngine('attach', {promptPosition : "centerRight"});
    $("input[type=radio]").change(function(e){
        e.preventDefault();
        if ( $('#some').is(':checked')){
            $('#emails').removeAttr("disabled");
        } else {
            $('#emails').attr("disabled", true);
        }
    });
});
</script>
