<!--afisare mesaje de eroare/succes-->
<?php if(!empty($this->message)) : ?>
	<?php foreach($this->message as $value) : ?>
		<center><?php echo $value; ?></center>
	<?php endforeach; ?>
	<div class="clear"></div>
<?php endif; ?>
<div class="col-md-6">
<button class="btn btn-primary" onclick="location.href='<?php echo WEBROOT; ?>doctors'" title="Inapoi" >&laquo; Inapoi</button>

<div class="clear">&nbsp;</div>
    <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Editeaza</h3>
        </div>
        <?php echo $this->formEditUser; ?>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$('#idRole').change(function(){
		if($(this).val() = 14)
		{
			$('.multiClass').show();
			$('.selectClass').hide();
		}
		else
		{
			$('.multiClass').hide();
			$('.selectClass').show();
		}
	});
});
</script>