<form id="<?php echo $this->element->getId();?>" class="<?php echo $this->element->getAttrib('class');?>" action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod();?>" enctype="<?php echo $this->element->getEncType();?>">
    <div class="col-md-5"> 
        <div class="col-md-12">
            <div class="widget-container fluid-height clearfix">
                <div class="heading">
                    <i class="fa fa-table"></i>Adauga agent
                    <div class="pull-right">
                        <a class="tooltip-trigger" data-placement="top" data-toggle="tooltip" style="width:60%;display:none;" href="javascript:;"><i class="fa fa-info-circle"></i></a>
                    </div>
                </div>
                <div class="padded">
                    <?php echo $this->{$this->element->agent->helper}(
                        $this->element->agent->getName(),
                        $this->element->agent->getValue(),
                        $this->element->agent->getAttribs()
                        
                    );?>                    
                    <?php if(($this->element->agent->getMessages())){ echo  $this->formErrors($this->element->agent->getMessages());}?>
                </div>
                <div class="padded">
                    <?php echo $this->{$this->element->car->helper}(
                        $this->element->car->getName(),
                        $this->element->car->getValue(),
                        $this->element->car->getAttribs(),
                        $this->element->car->getMultiOptions()
                    );?>                    
                    <?php if(($this->element->car->getMessages())){ echo  $this->formErrors($this->car->car->getMessages());}?>
                </div>                                              
                <div class="padded">           
                    <?php echo $this->{$this->element->submit->helper}(
                        $this->element->submit->getName(),
                        $this->element->submit->getValue(),
                        $this->element->submit->getAttribs()
                    );?>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="clear"></div>
<script type="text/javascript">
$(document).ready(function() {
	$('#<?php echo $this->element->getId();?>').validationEngine('attach', {promptPosition : "centerRight"});
});
</script>
