<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" enctype="<?php echo $this->element->getEncType();?>">			
    <?php echo $this->{$this->element->action->helper}(
        $this->element->action->getName(),
        $this->element->action->getValue(),
        $this->element->action->getAttribs()
    );?>
    <div class="padded"><!--dupa nume-->
        <?php echo $this->{$this->element->nameSearch->helper}(
            $this->element->nameSearch->getName(),
            $this->element->nameSearch->getValue(),
            $this->element->nameSearch->getAttribs()
        );?>
        <?php if(($this->element->nameSearch->getMessages())){ echo  $this->formErrors($this->element->nameSearch->getMessages());}?>
    </div>   
    <div class="padded"><!--dupa email-->		
        <?php echo $this->{$this->element->emailSearch->helper}(
            $this->element->emailSearch->getName(),
            $this->element->emailSearch->getValue(),
            $this->element->emailSearch->getAttribs()
        );?>
        <?php if(($this->element->emailSearch->getMessages())){ echo  $this->formErrors($this->element->emailSearch->getMessages());}?>
    </div>  
    <div class="clear"></div>
    <div class="padded"><!--submit-->
        <?php echo $this->{$this->element->search->helper}(
            $this->element->search->getName(),
            $this->element->search->getValue(),
            $this->element->search->getAttribs()
        );?>
        <a href="javascript:;" class="btn btn-primary reset">Reset</a>
    </div>  
</form>