<!--afisare mesaje de eroare/succes-->
<?php if(!empty($this->message)) : ?>
	<?php foreach($this->message as $value) : ?>
		<center><?php echo $value; ?></center>
	<?php endforeach; ?>
	<div class="clear"></div>
<?php endif; ?>
    
<div class="col-md-8">
	<div class="col-md-12">
		<button class="btn btn-primary" onclick="location.href='<?php echo WEBROOT; ?>agents'" title="<?php echo Zend_Registry::get('translate')->_('back'); ?>' " >&laquo; <?php echo Zend_Registry::get('translate')->_('back'); ?></button>
	</div>
</div>    
<div class="clear">&nbsp;</div>
<?php echo $this->formEditUser; ?>

<script type="text/javascript">
$(document).ready(function(){
	$('#idRole').change(function(){
		if($(this).val() = 1)
		{
			$('.multiClass').show();
			$('.selectClass').hide();
		}
		else
		{
			$('.multiClass').hide();
			$('.selectClass').show();
		}
	});
});
</script>