<div class="col-md-12">
    <?php if(!empty($this->message)) : ?>
    <?php foreach($this->message as $value) : ?>
        <center class="w670"><?php echo $value; ?></center>
    <?php endforeach; ?>
    <div class="clearfix">&nbsp;</div>
<?php endif; ?>
</div>
<div class="clear"></div>
<div class="page-title">
    <h1>
      Pipeline
    </h1>
</div>
<div class="col-md-8">
    <div class="col-md-12">        
        <?php if(Needs_Roles::hasAccess(Zend_Registry::get('user')->getIdRole(),'adaugare_client')){  ?>		
            <a class="add_button_grey" href="<?php echo WEBROOT; ?>clients/add">Adauga client</a>                    						
        <?php } ?>
    </div>
</div>
<div class="clear">&nbsp;</div>
<!-- Agents -->
<div class="row">
  <div class="col-lg-12">
    <div class="widget-container fluid-height clearfix">     
      <div class="heading">
        <i class="fa fa-table"></i>Agenti        
      </div>
      <div class="widget-content padded clearfix">
        <?php if($this->result){?>
        <table class="table table-bordered table-striped" id="dataTable1">
          <thead>
            <th>
              Agent
            </th>
            <th>
              Client/Companie
            </th>
            <th class="hidden-xs">
              Adresa client/Judet/Oras
            </th>
            <th class="hidden-xs">
              Produse cerute/comercializate
            </th>
            <th class="hidden-xs">
              Ultima vizita
            </th>          
          </thead>
          <tbody>            
            <?php foreach ($this->result as $value) {?>
            <tr>
              <td>
                <a title="Vizualizare" target="_blank" class="table-actions btn btn-info-outline" href="<?php echo WEBROOT; ?>agents/view/id/<?php echo $value->getId(); ?>/client/<?php echo $value->getIdClient(); ?>"><?php echo $value->getName(); ?></a>
                <?php if($value->getStatus() == 1){ ?>
                    <img src="<?php echo WEBROOT; ?>theme/admin/images/icons/icon-active.png">
                <?php }else{ ?>   
                    <img src="<?php echo WEBROOT; ?>theme/admin/images/icons/icon-offline.png">
                <?php } ?>                 
              </td>
              <td>                 
                  <?php if($value->getIsClient() === 1 ){ ?>
                  <b style="color:#007aff;"><?php  echo $value->getClient(); ?><br><?php echo $value->getCompany(); ?></b> 
                  <?php }else{ ?>
                    <?php  echo $value->getClient(); ?><br><?php echo $value->getCompany(); ?>
                  <?php } ?>
              </td> 
              <td class="hidden-xs">
                  <?php echo $value->getAddress(); ?><br><?php echo Needs_Tools::getCityById($value->getIdCity()).',' ?><?php echo Needs_Tools::getCountyById($value->getIdCounty()); ?>
              </td>
              <td class="hidden-xs">
                <?php echo $value->getProducts(); ?>
              </td>        
             
              <td class="hidden-xs" style="text-align:center;padding:10px 0px;">
                <?php echo Needs_Tools::getLastAgentVisit($value->getId(), $value->getIdClient()); ?>
                  <br>
                  <b><?php echo Needs_Tools::getTotalMonthVisitsByIdClient($value->getIdClient()); ?></b> vizite in luna curenta
              </td>                            
            </tr>            
            <?php }?>
          </tbody>
        </table>
            <?php }else{ ?>           
                <div class="col-md-6 pull-left"><h3>Nu exista clienti asociati agentilor.</h3></div>         
            <?php } ?>          
      </div>
    </div>    
  </div>
</div>
<script>
	$(document).ready(function(){
		$('.confirmDelete').click(function(){
			var link = $(this);
			$("#confirmDelete").dialog({
				bgiframe: true,
				height: 140,
				width: 400,
				modal: true,
				buttons:{
					'<?php echo Zend_Registry::get('translate')->_('yes'); ?>': function(){
						$(this).dialog('close').dialog('destroy');
						window.location.href = link.attr('href');
					},
					'<?php echo Zend_Registry::get('translate')->_('no'); ?>': function(){
						$(this).dialog('close').dialog('destroy');
						window.location.reload();
					}
				}
			});
			return false;
		});             
            }); 	
</script>