<div class="col-md-12">
    <?php if(!empty($this->message)) : ?>
        <?php foreach($this->message as $value) : ?>
            <center style='width: 360px;margin: 0 auto;'><?php echo $value; ?></center>
        <?php endforeach; ?>
        <div class="clearfix">&nbsp;</div>
    <?php endif; ?>
</div>
<div class="login-box">
  <div class="login-box-body">
      <?php echo $this->form; ?>
  </div>
</div>
