<!-- BEGIN: Show error messages -->
<?php if(!empty($this->message)):?>
	<?php foreach($this->message as $value):?>
		<center><?php echo $value; ?></center>
	<?php endforeach; ?>
	<div class="clearfix">&nbsp;</div>
<?php endif;?>
<!-- END: Show error messages -->
<div class="col-md-6">
<button class="btn btn-primary" onclick="location.href='<?php echo WEBROOT; ?>newsletter'" title="Inapoi" >&laquo; Inapoi</button>

<div class="clear">&nbsp;</div>

    <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Adauga Newsletter</h3>
        </div>
    <?php echo $this->form; ?>
    </div>
</div>

