<div class="col-md-12">
    <?php if(!empty($this->message)) : ?>
    <?php foreach($this->message as $value) : ?>
        <center class="w670"><?php echo $value; ?></center>
    <?php endforeach; ?>
    <div class="clearfix">&nbsp;</div>
<?php endif; ?>
</div>
<div class="btn-group margin-bottom">
    <a href="<?php echo WEBROOT; ?>newsletter/add" class="btn btn-primary btn-block"><b>Adauga newsletter</b></a>
</div>
<div class="clear"></div>
<div class="box">
<!--    <div class="box-header">
      <h3 class="box-title">Comanda</h3>
    </div>-->
    <!-- /.box-header -->
    <div class="box-body">
      <table id="clienti" class="table table-bordered table-striped">
        <thead>              
        <tr>
          <th>Numar</th>
          <th>Titlu</th>
          <th>Mesaj</th>
          <th>Imagine</th>
          <th>Trimis la</th>
          <th>Data</th>
        </tr>
        </thead>
        <tbody>
        <?php 
        if($this->result) {
            foreach($this->result as $value){ ?>
            <tr>
               <?php 
               $client = Needs_Tools::getClientByComandaId($value->getId());
               ?>
              <td> <?php echo $value->getId(); ?> </td>
              <td> <?php echo $value->getTitle(); ?> </td>
              <td> <?php echo $value->getMessage(); ?> </td>
              <td> <a href='<?php echo WEBROOT; ?>data/uploads/<?php echo $value->getImage(); ?>' class='fancybox' ><?php echo $value->getImage(); ?></a> </td>
              <td> <?php echo $value->getSent(); ?> </td>
              <td> <?php echo date('d-m-Y', $value->getCreated()); ?></td>
            </tr>
            <?php
            }
        } ?>
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
</div>
<div class="clear"></div>
<script>
$(document).ready(function(){
    $(function () {
        $('#clienti').DataTable({
                    "language": {
                    "sProcessing":   "Proceseaza...",
                    "sLengthMenu":   "Afiseaza _MENU_ inregistrari pe pagina",
                    "sZeroRecords":  "Nu am gasit nimic - ne pare rau",
                    "sInfo":         "Afisate de la _START_ la _END_ din _TOTAL_ inregistrari",
                    "sInfoEmpty":    "Afisate de la 0 la 0 din 0 inregistrari",
                    "sInfoFiltered": "(filtrate dintr-un total de _MAX_ inregistrari)",
                    "sInfoPostFix":  "",
                    "sSearch":       "Cauta:",
                    "sUrl":          "",
                    "oPaginate": {
                        "sFirst":    "Prima",
                        "sPrevious": "Precedenta",
                        "sNext":     "Urmatoarea",
                        "sLast":     "Ultima"
                    }
                }
            } );
        } );
    $('[data-toggle="tooltip"]').tooltip(); 
    $(".fancybox").fancybox({
        'width'         : '80%',
        'height'        : '100%',
        'autoScale'     : true,
        'transitionIn'  : 'none',
        'transitionOut' : 'none'
    });
});
</script>