<div class="col-md-12">
    <?php if(!empty($this->message)) : ?>
        <?php foreach($this->message as $value) : ?>
            <center class="w670"><?php echo $value; ?></center>
        <?php endforeach; ?>
        <div class="clearfix">&nbsp;</div>
    <?php endif; ?>
<div class="box">
    <div class="box-body">
      <?php if($this->result){
        foreach($this->result as $value){ ?>
      <table class="table">
        <tbody>
          <tr>
            <td style="width:20%;" class="category"><strong>NUME</strong></td>
            <td>
              <p><?php echo $value->getName(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>EMAIL</strong></td>
            <td>
              <p><?php echo $value->getEmail(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>ADRESA</strong></td>
            <td>
              <p><?php echo $value->getAddress(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>DATA NASTERII</strong></td>
            <td>
              <p><?php echo date('d-m-Y', $value->getBirth_date()); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>VARSTA</strong></td>
            <td>
              <p><?php echo $value->getAge(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>OCUPATIE</strong></td>
            <td>
              <p><?php echo $value->getOcupation(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>CNP</strong></td>
            <td>
              <p><?php echo $value->getCnp(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>CI</strong></td>
            <td>
              <p><?php echo $value->getCi(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>PHONE NUMBER</strong></td>
            <td>
              <p><?php echo $value->getPhone_number(); ?></p>
            </td>
          </tr>
          <tr>
              <td style="width:20%;" class="category"><strong>OBSERVATII</strong></td>
              <td>
                  <?php
                    $observations = Needs_Tools::getObservationsByPacient($value->getId());
                    if($observations){
                        $text = '';
                        foreach($observations as $observation){
                            $text .= '<p><span style="display:block;float:left;width: 11%;font-weight: bold;">'.date('d-m-Y H:i', $observation->getCreated()).' : </span> ';
                            $text .= '<span style="margin-left: 10px;float:left;display:block;width: 80%;">'.$observation->getObservation().'</span></p>';
                            $text .= '<span>'.Needs_Tools::getUserById($observation->getDoctor()).'</span></p>';
                        }
                    } else {
                        $text = 'Nu exista observatii!';
                    }
                  ?>
                  <p><?php echo $text; ?></p>
              </td>
          </tr>
          <?php if($this->role == 2){ ?>
          <tr>
              <td style="width:20%;" class="category"><strong>Adauga observatie</strong></td>
              <td>
                <form method="POST">
                    <div class="form-group">
                        <textarea cols="100" rows="5" id="observatie" name="observatie" value=""></textarea>
                    </div>
                    <button type="submit" id="submitObs" class="btn btn-default">Trimite</button>
                </form>
              </td>
          </tr>
          <?php } ?>
        </tbody>
      </table>
      <?php }
    } ?>
    </div>
  </div>