<div class="box">
    <div class="box-body">
      <?php if($this->result){
        foreach($this->result as $value){ ?>
      <table class="table">
        <tbody>
          <tr>
            <td style="width:20%;" class="category"><strong>NUME</strong></td>
            <td>
              <p><?php echo $value->getName(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>EMAIL</strong></td>
            <td>
              <p><?php echo $value->getEmail(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>ADRESA</strong></td>
            <td>
              <p><?php echo $value->getAddress(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>DATA NASTERII</strong></td>
            <td>
              <p><?php echo date('d-m-Y', $value->getBirth_date()); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>VARSTA</strong></td>
            <td>
              <p><?php echo $value->getAge(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>OCUPATIE</strong></td>
            <td>
              <p><?php echo $value->getOcupation(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>CNP</strong></td>
            <td>
              <p><?php echo $value->getCnp(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>CI</strong></td>
            <td>
              <p><?php echo $value->getCi(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>PHONE NUMBER</strong></td>
            <td>
              <p><?php echo $value->getPhone_number(); ?></p>
            </td>
          </tr>
          <tr>
            <td style="width:20%;" class="category"><strong>OBSERVATII</strong></td>
            <td>
              <p><?php echo $value->getPhone_number(); ?></p>
            </td>
          </tr>
        </tbody>
      </table>
      <?php }
    } ?>
    </div>
  </div>