<div class="col-md-12">
    <?php if(!empty($this->message)) : ?>
    <?php foreach($this->message as $value) : ?>
        <center class="w670"><?php echo $value; ?></center>
    <?php endforeach; ?>
    <div class="clearfix">&nbsp;</div>
<?php endif; ?>
</div>

<div class="btn-group margin-bottom">
    <a href="" data-toggle="modal" data-target="#modal-add" class="btn btn-primary btn-block"><b>Adauga programare</b></a>
</div>

<div class="clear"></div>
<div class="box">
<!--    <div class="box-header">
      <h3 class="box-title">Comanda</h3>
    </div>-->
    <!-- /.box-header -->
    <div class="box-body">
        <table id="programari" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Doctor</th>
                <th>Pacient</th>
                <th>Data</th>
            </tr>
            </thead>
            <tbody>
            <?php
            if($this->result) {
                foreach($this->result as $value){ ?>
                    <tr>
                        <td> <?php echo Needs_Tools::getUserById($value->getIdDoctor()); ?> </td>
                        <td> <?php echo Needs_Tools::getUserById($value->getIdPacient()); ?> </td>
                        <td> <?php echo date('d-m-Y', $value->getData()).' - '.$value->getOra(); ?> </td>
                    </tr>
                <?php }
            } ?>
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
</div>
<div class="clear"></div>
<div id='modal-add' class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <form method="POST" action="<?php echo WEBROOT; ?>programari/add" >
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Adauga programare</h4>
                </div>
                <div class="modal-body">
                    <select id="doctorSelect" name="doctor">
                        <?php foreach($this->users as $users){
                            echo '<option value="'.$users->getId().'">'.$users->getName().'</option>';
                        } ?>
                    </select>

                    <input type="hidden" id="type" name="type" value="<?php echo $this->type ?>">
                    <input type="text" id="date" name="date" value="">
                    <select id="hourSelect" class="hidden" name="hour" value="">

                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Inchide</button>
                    <button type="submit" class="btn btn-primary" >Programeaza</button>
                    <!--<button type="button" class="btn btn-primary">Sterge</button>-->
                </div>
            </div><!-- /.modal-content -->
        </form>
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    $(document).ready(function() {

        $('#date').datepicker({minDate: 0});
        $('#doctorSelect').on('change', function(){
            $('#hourSelect').addClass('hidden');
            $('#date').val("");
        });
        $('#date').on('change', function(){
            $('#hourSelect').empty();
            if($('#type').val() == 'doctor'){
                var doctorId    = <?php echo $this->userId; ?>;
            } else {
                var doctorId    = $('#doctorSelect').val();
            }
            var date            = $('#date').val();
            $.ajax({
                type: "POST",
                url: "<?php echo WEBROOT; ?>ajax/get-hours-by-id-doctor",
                data:{doctorId: doctorId, date: date}
            }).done(function(result){
                if(result){
                    $('#hourSelect').append(result);
                    $('#hourSelect').removeClass('hidden');
                }
            });
        });
    });
</script>