<div class="box">
    <div class="col-md-12">
        <?php if(!empty($this->message)) : ?>
        <?php foreach($this->message as $value) : ?>
            <center class="w670"><?php echo $value; ?></center>
        <?php endforeach; ?>
        <div class="clearfix">&nbsp;</div>
    <?php endif; ?>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table id="clienti" class="table table-bordered table-striped">
        <thead>              
        <tr>
          <th>Nr. Comanda</th>
          <th>Client</th>
          <th>Tip</th>
          <th>Nume</th>
          <th>Detalii</th>
          <th>Data</th>
          <th>Finalizeaza etapa</th>
        </tr>
        </thead>
        <tbody>
        <?php 
        if($this->result) {
            foreach($this->result as $value){ ?>
            <tr>
               <?php 
               $client = Needs_Tools::getClientByComandaId($value->getId());
               if($client){
                   $judet       = Needs_Tools::getNivel1ById($client->getId_nivel1());
                   $localitate  = Needs_Tools::getNivel2ById($client->getId_nivel2());
                   $client      = '<a href="#" style="display:block;" data-toggle="tooltip" title="'.$judet.' / '.$localitate.'  '.$client->getTelefon().'  '.$client->getEmail().'">'.$client->getNume().'</a>';
               } else {
                   $client      = ' - ';
               }
               ?>
              <td> <?php echo $value->getNumar(); ?> </td>
              <td> <?php echo $client; ?> </td>
              <td> <?php echo Needs_Tools::getTipComandaById($value->getTip()); ?> </td>
              <td> <?php echo $value->getNume(); ?> </td>
              <td> <?php echo $value->getDetalii(); ?></td>
              <?php
                $utilizator     = Needs_Tools::getDepartamentComandaById($value->getId());
                if($utilizator) {
                    $departament    = Needs_Tools::getLevelById($utilizator->getIdRole());
                    $status = $utilizator->getName().' - '.$departament;
                } else {
                    $status = ' -- ';
                }
                
              ?>
              <td> <?php echo date('d-m-Y', $value->getCreated()); ?></td>
              <td> <a href='#0' title='Finalizeaza' data-toggle="modal" data-target="#modal-<?php echo $value->getId(); ?>"><i class="glyphicon glyphicon-ok"></i></a></td>
            </tr>
            <div id='modal-<?php echo $value->getId(); ?>' class="modal fade" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title">Confirmare finalizare etapa</h4>
                    </div>
                    <div class="modal-body">
                        <p>Sunteti sigur ca doriti sa finalizati etapa <?php echo $departament; ?> pentru comanda: <strong><?php echo $value->getNume(); ?></strong> ?</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Inchide</button>
                      <a class="btn btn-primary" href="<?php echo WEBROOT; ?>comanda/send-next/id/<?php echo $value->getId(); ?>">Finalizeaza</a>
                    </div>
                  </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
            <?php }
        } ?>
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
</div>
<div class="clear"></div>
<script>
$(document).ready(function(){
    $(function () {
        $('#clienti').DataTable({
                "language": {
                "sProcessing":   "Proceseaza...",
                "sLengthMenu":   "Afiseaza _MENU_ inregistrari pe pagina",
                "sZeroRecords":  "Nu am gasit nimic - ne pare rau",
                "sInfo":         "Afisate de la _START_ la _END_ din _TOTAL_ inregistrari",
                "sInfoEmpty":    "Afisate de la 0 la 0 din 0 inregistrari",
                "sInfoFiltered": "(filtrate dintr-un total de _MAX_ inregistrari)",
                "sInfoPostFix":  "",
                "sSearch":       "Cauta:",
                "sUrl":          "",
                "oPaginate": {
                    "sFirst":    "Prima",
                    "sPrevious": "Precedenta",
                    "sNext":     "Urmatoarea",
                    "sLast":     "Ultima"
                }
            }
        });
    });
});
</script>