<header class="main-header">
    <!-- Logo -->
    <a href="<?php echo WEBROOT; ?>pacienti" class="logo">
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Dental MS</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <?php
            $auth	 = Zend_Auth::getInstance()->setStorage(new Zend_Auth_Storage_Session());
            if($auth->hasIdentity()){
                $accountAuth = $auth->getStorage()->read();
                if($accountAuth->getIdRole() == 1){
                    $class = '';
                } else {
                    $class = 'hidden';
                }
            }
            ?>
            <li class="user-header" style="margin-top: 14px;color: #fff;">
                <?php
                    if($auth->hasIdentity()){
                        $accountAuth = $auth->getStorage()->read();
                        echo $accountAuth->getName();
                    } else {
                        echo 'Unknown';
                    }

                ?>
            </li>
            <li>
                <a href="<?php echo WEBROOT; ?>auth/logout"><i class="glyphicon glyphicon-log-out"></i></a>
            </li>
        </ul>
      </div>

    </nav>
</header>
<aside class="main-sidebar">
    <section class="sidebar">
        <?php
            $this->setEscape('trim'); // will allow html and remove escaping
            echo $this->navigation()->menu()->setMaxDepth(0)->setUlClass('sidebar-menu')->renderMenu($this->{'header'});
            $this->setEscape('htmlspecialchars'); // restore escaping mechanism
        ?>
    </section>
</aside>
