<ul class="timeline">
    <?php 
    if(count($this->result) > 0) {
        for($i = 0;$i < count($this->result);$i++){
            if((date('d-m-Y',$this->firstDate) == date('d-m-Y',$this->result[$i]->getCreated()) && $i == 0) || date('d-m-Y',$this->result[$i]->getCreated()) != date('d-m-Y',$this->result[$i-1]->getCreated())){ ?>
            <!-- timeline time label -->
            <li class="time-label">
                <span class="bg-blue">
                    <?php echo date('d-m-Y',$this->result[$i]->getCreated()); ?>
                </span>
            </li>
            <!-- /.timeline-label -->
       <?php }          
    ?>
    <!-- timeline item -->
    <li>
        <!-- timeline icon -->
        <?php 
        switch ($this->result[$i]->getTip()) {
            case 'add':
                $icon = 'fa-plus bg-blue';
                break;
            case 'edit':
                $icon = 'fa-edit bg-yellow';

                break;
            case 'delete':
                $icon = 'fa-minus bg-red';

                break;
            case 'send':
                $icon = 'fa-send bg-green';

                break;

            default:
                $icon = 'fa-envelope bg-blue';
                break;
        }
        ?>
        <i class="fa <?php echo $icon;?>"></i>
        <div class="timeline-item">
            <span class="time"><i class="fa fa-clock-o"></i> <?php echo date('H:i',$this->result[$i]->getCreated()); ?></span>
            
            <h3 class="timeline-header"><?php echo Needs_Tools::getUserById($this->result[$i]->getUserId()); ?></h3>
            
            <div class="timeline-body">
                <?php $comanda  = Needs_Tools::getComandaById($this->result[$i]->getComandaId()); ?>
                <?php 
                if($this->result[$i]->getDepartamentInitial() > 0){
                    $utilizator     = Needs_Tools::getDepartamentComandaById($this->result[$i]->getComandaId());
                   
                    if($utilizator) {
                        $departament    = Needs_Tools::getLevelById($utilizator->getIdRole());
                        $status = $utilizator->getName().' - '.$departament;
                    } else {
                        $departamentNou = Needs_Tools::getDepByComanda($this->result[$i]->getComandaId());
                        if($departamentNou == 90){
                            $status = '<span class="label label-warning">Se asteapta acceptare machetare!</span>';
                        }elseif($departamentNou == 91){
                            $status = '<span class="label label-success">Comanda expediata!</span>';
                        }else{
                            $status = 'Fara status!'; 
                        }
                    }
                    
                    echo Needs_Tools::getUserById($this->result[$i]->getUserId()).' '.$this->result[$i]->getVerb().' '.$comanda->getNume().' in '.$status.' ';
                } else {
                    echo Needs_Tools::getUserById($this->result[$i]->getUserId()).' '.$this->result[$i]->getVerb().'  '.$comanda->getNume(); 
                }
                
                ?>
                
            </div>
        </div>
    </li>
    <!-- END timeline item -->
    <?php }  ?> 
    <?php } else { ?> 
    <li>
        <!-- timeline icon -->
        <i class="fa fa-envelope bg-blue"></i>
        <div class="timeline-item">
            <span class="time"><i class="fa fa-clock-o"></i> 12:05</span>

            <h3 class="timeline-header"><a href="#">Support Team</a> ...</h3>

            <div class="timeline-body">
                Nu exista loguri
            </div>

            <div class="timeline-footer">
                <a class="btn btn-primary btn-xs">...</a>
            </div>
        </div>
    </li>
    <?php } ?> 
</ul>