<div class="col-md-12">
    <?php if(!empty($this->message)) : ?>
    <?php foreach($this->message as $value) : ?>
        <center class="w670"><?php echo $value; ?></center>
    <?php endforeach; ?>
    <div class="clearfix">&nbsp;</div>
<?php endif; ?>
</div>
<!--KM DPO-->
<div class="row">
    <!-- Hover Row Table -->
    <div class="col-lg-12">
      <div class="widget-container fluid-height clearfix">
        <div class="heading">
          <i class="fa fa-truck"></i>INDEX AUTOTURISME DEPODENT
        </div>
        <div class="widget-content padded clearfix">  
        <?php if($this->result){?>
            <table class="table">
                <thead>
                  <th>
                    Agent
                  </th>
                  <th>
                    Autoturism
                  </th>
                  <th>
                    Luna
                  </th>
                  <th>
                    Index luna precedenta
                  </th>
                  <th>
                    Index luna curenta
                  </th>
                  <th>
                    KM Totali luna curenta
                  </th>
                  <th>
                    KM Firma
                  </th>
                  <th>
                    KM Personali
                  </th>             

                  <th></th>
                </thead>
                <tbody>                             
                    <tr>
                      <td>
                        <?php echo Needs_Tools::getAgentById($this->result->getIdAgent()); ?>
                      </td>
                      <td> 
                          <?php echo Needs_Tools::getCarById(Zend_Registry::get('user')->getIdCar()); ?>
                      </td>
                      <td> 
                          <?php echo Needs_Tools::getMonthByAgentId(Zend_Registry::get('user')->getId());?>
                      </td>
                      <td id="oldIndex"></td>
                      <td id="currentIndex"></td>
                      <td id="totalKm"></td> 
                      <td id="workKm"></td>
                      <td id="personalKm"></td>                                    
                      <td id="addIndex">
                          <button id="submitIndex" class="btn btn-default" type="submit">Adauga</button>
                      </td>
                    </tr>                  
                </tbody>            
            </table>            
            <div class="widget-content padded">
                <div class="alert alert-info">
                     <?php echo Needs_Tools::getLastRevisionDateByCarId($this->result->getIdCar()); ?>                    
                </div>
                <div style='width:170px;'>
                    <p>Adauga data ultimei revizii: </p>
                    <div data-date-format="dd-mm-yyyy" data-date-autoclose="true" class="input-group date datepicker" style="padding:0px;">
                        <input type="text" id="serviceDate" class="form-control" placeholder="Selecteaza data"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>                                                                                                  
                    </div>
                    <div class="clear">&nbsp;</div>
                    <button id="addService" class="btn btn-lg btn-default">Adauga</button>
                    <div class="clear">&nbsp;</div>                    
                </div>
                <?php echo Needs_Tools::getLastServiceKmByAgentId($this->result->getIdAgent())  ?>
            </div> 
            <?php }elseif($this->resultA){ ?>                                  
                <table class="table">
                    <thead>
                      <th>
                        Agent
                      </th>
                      <th>
                        Autoturism
                      </th>
                      <th>
                        Luna
                      </th>
                      <th>
                        Index luna <?php echo date('M',strtotime('-2 month')) ?>
                      </th>
                      <th>
                        Index luna <?php echo date('M',strtotime('-1 month')) ?>
                      </th>
                      <th>
                        KM Totali 
                      </th>
                      <th>
                        KM Firma
                      </th>
                      <th>
                        KM Personali
                      </th>                                 
                    </thead>
                    <tbody> 
                        <?php foreach ($this->resultA as $value) { ?>
                        <tr>
                          <td>
                            <?php echo Needs_Tools::getAgentById($value->getIdAgent()); ?>
                          </td>
                          <td>
                            <a href="<?php echo WEBROOT; ?>distance/view/id/<?php echo $value->getIdAgent() ?>" class="viewCar" ><?php echo Needs_Tools::getCarById($value->getIdCar()); ?></a>
                          </td>
                          <td>  
                              <?php echo date('M',strtotime('-1 month')) ?>
                          </td>
                          <td id="oldIndex"><?php echo $value->getLastKmIndex(); ?></td>  
                          <td id="currentIndex"><?php echo $value->getNewKmIndex(); ?></td>
                          <td id="totalKm"><?php echo $value->getWorkKm()+$value->getPersonalKm(); ?></td> 
                          <td id="workKm"><?php echo $value->getWorkKm(); ?></td>
                          <td id="personalKm"><?php echo $value->getPersonalKm(); ?></td>                                                              
                        </tr>  
                        <?php } ?>
                    </tbody>            
                </table>                          
            <?php }else{ ?>                                  
                <div class="col-md-6 pull-left"><h2>Indexul pe luna trecuta nu a fost adaugat!</h2></div>                                  
            <?php } ?>
        </div>
      </div>
    </div>
</div>
<?php if($this->result){?>
<script type="text/javascript"> 
   
    $(document).ready(function(){
        $(document).on('keyup','#newIndex',function(){
            var previousIndex = <?php echo $this->result->getNewKmIndex(); ?>;     
            var sum = $('#newIndex').val()-previousIndex;
            var totalKM = parseFloat(sum).toFixed(2);
            $('#totalKm').html(totalKM);
	
            $(document).on('keyup','#dpoKm',function(){

                    var sumPersonalKM = totalKM - $('#dpoKm').val();
                    var personalKM = parseFloat(sumPersonalKM).toFixed(2);
                    $('#personalKm').html(personalKM);
            });
        });
        //    get comment by date
        $('#selectMonth').change(function (e) {
            e.preventDefault();
            
            var monthId = $(this).val();
            var agentId = "<?php echo $this->result->getIdAgent() ?>";
//            console.log(monthId,agentId);
//            var d = new Date();
//            var n = d.getMonth(); 
//            if(monthId === n) {                 
//               $('#addIndex').append('<button id="submitIndex" class="btn btn-default" type="submit">Adauga</button>');
//            }
                      
            $.ajax({
                type:"POST",
                url:"<?php echo WEBROOT; ?>ajax/get-distance",
                data: {monthId: monthId, agentId: agentId}
            })
            .done(function(msg){
                if(msg){
                    data = jQuery.parseJSON(msg);
                }

                if(data){                    
                    lastKmIndex=data['lastKmIndex'];                                                                                    
                    newKmIndex=data['newKmIndex'];                                                                                    
                    totalKm=data['totalKm'];                                                                                     
                    workKm=data['workKm'];                                                                                    
                    personalKm=data['personalKm'];                                                                                    
                };     

//                $('#oldIndex').html(lastKmIndex); 
                if(lastKmIndex !== null){
                $('#oldIndex').html(lastKmIndex);
                $('#submitIndex').hide();
                }else if(monthId === "") {
                    $('#oldIndex').html('');
                }
                else{
                    $('#oldIndex').html('<?php echo $this->result->getNewKmIndex() ?>');
                    $('#submitIndex').show();
                }
                if(newKmIndex !== null){
                    $('#currentIndex').html(newKmIndex); 
                }else if(monthId === "") {
                    $('#currentIndex').html('');
                }else{
                    $('#currentIndex').html('<input class="form-control" id="newIndex" placeholder="" type="text">');
                }
                if(totalKm !== 0){
                $('#totalKm').html(totalKm);
                }else if(monthId === "") {
                    $('#totalKm').html('');
                }else{
                    $('#totalKm').html('0');
                }
                if(workKm !== null){
                    $('#workKm').html(workKm); 
                }else if(monthId === "") {
                    $('#workKm').html('');
                }else{
                    $('#workKm').html('<input class="form-control" id="dpoKm" placeholder="" type="text">');
                }
                if(personalKm !== 0){
                $('#personalKm').html(personalKm);
                }else if(monthId === "") {
                    $('#personalKm').html('');
                }else{
                    $('#personalKm').html('0');
                }
            });             
            return false;
        });
        
        // add km index for current month
    
    });
    $('#submitIndex').click(function (e) {
        e.preventDefault(); 
//        alert('intra');
        var agentId = "<?php echo $this->result->getIdAgent() ?>";
        var monthId = $('#selectMonth').val();
        var oldIndex = "<?php echo $this->result->getNewKmIndex(); ?>";
        var newIndex = $('#newIndex').val();
        var workKm = $('#dpoKm').val();    
        var personalKm = ($('#newIndex').val() - "<?php echo $this->result->getNewKmIndex() ?>")-workKm;    
//        console.log([monthId,oldIndex,newIndex,workKm,personalKm]);
        if(monthId !== ""){
            if(newIndex !== "" && workKm !== ""){    
                $.ajax({
                    type:"POST",
                    url: "<?php echo WEBROOT; ?>ajax/add-index",
                    data:{agentId: agentId, monthId: monthId, oldIndex: oldIndex, newIndex: newIndex, workKm: workKm, personalKm: personalKm}                   
                })
                .done(function(){         
                    alert('Indexul pe luna curenta a fost adaugat cu succes!'); 
                    window.location.reload();
                });
            }else{
                alert ('Completeaza toate campurile!');
            }
        }else{
            alert ('Selecteaza luna!');
        }
    });
    
    $('#addService').click(function (e) {
        e.preventDefault(); 
//        alert('intra');
        var agentId = "<?php echo Zend_Registry::get('user')->getId(); ?>";
        var carId = "<?php echo Zend_Registry::get('user')->getIdCar(); ?>";
        var serviceDate = $('#serviceDate').val();
//        console.log([carId,serviceDate]);
        if(serviceDate !== ""){              
            $.ajax({
                type:"POST",
                url: "<?php echo WEBROOT; ?>ajax/add-service",
                data:{agentId: agentId,carId: carId,serviceDate: serviceDate}                   
            })
            .done(function(){         
                alert('Data reviziei a fost modificata cu succes!'); 
                window.location.reload();
            });            
        }else{
            alert ('Selecteaza data!');
        }
    });
</script>
<?php } ?>