<?php echo $this->doctype('HTML5'); ?>
<html>
<head>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta()
		->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
		->appendHttpEquiv('Content-Language', 'ro-RO')
		->appendHttpEquiv('expires', 'Wed, 26 Feb 2013 08:21:57 GMT')
		->appendHttpEquiv('pragma', 'no-cache')
		->appendHttpEquiv('Cache-Control', 'no-cache');
	?>
	<?php echo $this->headLink();?> 
	<?php echo $this->headStyle();?>
	<?php echo $this->headScript();?>
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
</head>

<body class="hold-transition login-page">
    <?php echo $this->layout()->content;?>
</body>
</html>
