<div id="content">
	<h1 style="font-size: 30px;"><?php echo Zend_Registry::get('translate')->_('ERROR_404_NOT_FOUND'); ?></h1>	
	<a class="btn btn-lg btn-default-outline" style="display: block; margin: 20px 0px;font-family: open sans;font-size:13px;color:#343434;" href="<?php echo WEBROOT ?>"><i class="fa fa-home"></i><?php echo Zend_Registry::get('translate')->_('ERROR_RETURN_HOME'); ?></a>
</div>
