<form id="<?php echo $this->element->getId();?>" class="<?php echo $this->element->getAttrib('class');?>" action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod();?>" enctype="<?php echo $this->element->getEncType();?>">
    <div class="box-body">
        <div class="form-group">
            <?php echo $this->{$this->element->nume->helper}(
                $this->element->nume->getName(),
                $this->element->nume->getValue(),
                $this->element->nume->getAttribs()
            );?>                    
            <?php if(($this->element->nume->getMessages())){ echo  $this->formErrors($this->element->nume->getMessages());}?>
        </div>                                            
        <?php echo $this->{$this->element->submit->helper}(
            $this->element->submit->getName(),
            $this->element->submit->getValue(),
            $this->element->submit->getAttribs()
        );?>
    </div>
</form>
<div class="clear"></div>
<script type="text/javascript">
$(document).ready(function() {
    $('#<?php echo $this->element->getId();?>').validationEngine('attach', {promptPosition : "centerRight"});
});
</script>
